#!/bin/bash
# gen_ancestry 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of evec_fn: '$evec_fn'"
    echo "Value of ancestry_fn: '$ancestry_fn'"
    echo "Value of thresh: '$thresh'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

	if test -z "$prefix"; then
		prefix=$(dx describe --name "$evec_fn" | sed 's/\.evec$//')
	fi

	WKDIR=$(mktemp -d)
	OUTDIR=$(mktemp -d)
	cd $WKDIR
	

    dx download "$evec_fn" -o evec
    dx download "$ancestry_fn" -o ancestry
    
    # remove "Other" from the ancestry; it's special!
    grep -v 'Other$' ancestry > ancestry_R
    # Format eigenvectors for loading into R
    tail -n+2 evec | sed -e 's/^  *//' -e 's/  *$//' -e 's/  */\t/g' -e 's/\t[^\t]*$//' > evec_R
    
    if test $(($num_evec + 1)) -gt "$(head -1 evec_R | tr '\t' '\n' | wc -l)"; then
    	dx-jobutil-report-error "ERROR: Desired number of eigenvectors exceeds the number of eigenvectors provided"
    fi
    
    # Now, we will assume that "ancestry" and "evec" are formatted correctly.
    # NOTE: the following should go into an R script...
    
    gen_ancestry.R ancestry_R evec_R $thresh $num_evec > $OUTDIR/$prefix.ancestry
    
    ancestry_out=$(dx upload $OUTDIR/$prefix.ancestry --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output ancestry_out "$ancestry_out" --class=file
}
