#!/bin/bash
# geno_p 0.0.1
# Generated by dx-app-wizard.
#
# Parallelized execution pattern: Your app will generate multiple jobs
# to perform some computation in parallel, followed by a final
# "postprocess" stage that will perform any additional computations as
# necessary.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() or any other entry point is ALWAYS
# executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

set -x

# install GNU parallel!
sudo sed -i 's/^# *\(deb .*backports.*\)$/\1/' /etc/apt/sources.list
sudo apt-get update
sudo apt-get install --yes parallel

sudo pip install pytabix

function parallel_download() {
	set -x
	cd $2
	dx download "$1"
	cd -
}
export -f parallel_download

function dl_part_index() {
	set -x
	echo "'$1', '$2', '$3', '$4'"
	cd "$2"
	fn=$(dx describe --name "$1")
	fn_base=$(echo "$fn" | sed 's/.vcf.gz$//')
	file_url=$(dx make_download_url "$1")
	idxfn=$(ls "$2/$fn.tbi")
	
	download_part.py -f "$file_url" -i "$idxfn" -L "$3" | tee "$4/$fn_base.$3.vcf" | bgzip -c > "$4/$fn_base.$3.vcf.gz"
	tabix -p vcf "$4/$fn_base.$3.vcf.gz"
}

export -f dl_part_index

function dl_index() {
 	set -x
	echo "'$1', '$2', '$3'"
 	cd "$2"
 	fn=$(dx describe --name "$1")
	dx download "$1" -o "$fn"
	if test -z "$(ls $fn.tbi)"; then
		tabix -p vcf $fn
	fi
	echo "$2/$fn" >> $3
}

export -f dl_index


main() {

	export SHELL="/bin/bash"
	ADDL_CMD=""

	SUBJOB_ARGS=""
	if test "$target_file"; then
		tgt_id=$(dx describe "$target_file" --json | jq .id | sed 's/"//g')
		SUBJOB_ARGS="$SUBJOB_ARGS -itarget_file:file=$tgt_id"
	fi
	
	if test -z "$PREFIX"; then
		PREFIX="combined"
	fi
	
	WKDIR=$(mktemp -d)
	GVCF_SPLITDIR=$(mktemp -d)
	DXGVCF_LIST=$(mktemp)
	DXGVCFIDX_LIST=$(mktemp)
	
	cd $WKDIR
	
	# Get a list of chromosomes
	dx download "${gvcfidxs[0]}" -o test.vcf.gz.tbi
	CHROM_LIST=$(mktemp)
	tabix -l test.vcf.gz > $CHROM_LIST
	
	
	for i in "${!gvcfidxs[@]}"; do	
		echo "${gvcfidxs[$i]}" >> $DXGVCFIDX_LIST
	done
	
	for i in "${!gvcfs[@]}"; do
		echo "${gvcfs[$i]}" >> $DXGVCF_LIST
	done
	
	GVCF_LIST=$(dx upload $DXGVCF_LIST --brief)
	GVCFIDX_LIST=$(dx upload $DXGVCFIDX_LIST --brief)
	
	# Kick off each of those subjobs
	CIDX=0
	pparg=""
	while read chrom; do
		process_jobs[$CIDX]=$(dx-jobutil-new-job genotype_gvcfs -iPREFIX=$PREFIX.$chrom -ichrom=$chrom -ivcf_files:file="$GVCF_LIST" -ivcfidx_files:file="$GVCFIDX_LIST" $SUBJOB_ARGS)
		pparg="$pparg -ivcf_files=${process_jobs[$CIDX]}:vcf_out -ivcfidx_files=${process_jobs[$CIDX]}:vcfidx_out"
		CIDX=$((CIDX + 1))
	done < $CHROM_LIST
	
	# OK, now we simply have to merge all of the VCF files together
	postprocess=$(dx-jobutil-new-job merge_vcf $pparg -iPREFIX:string="$PREFIX" --depends-on ${process_jobs[@]})
	dx-jobutil-add-output vcf "$postprocess:vcf_out" --class=jobref
	dx-jobutil-add-output vcfidx "$postprocess:vcfidx_out" --class=jobref
}

genotype_gvcfs() {

	export SHELL="/bin/bash"
	ADDL_CMD=""

	if test "$target_file"; then
		dx download "$target_file" -o targets_raw.bed
		sed -n "/^$chrom[ \t].*/p" targets_raw.bed > targets.bed
		ADDL_CMD="-L $PWD/targets.bed"
	else
		ADDL_CMD="-L $chrom"
	fi
	
	if test -z "$PREFIX"; then
		PREFIX="combined"
	fi
	
	WKDIR=$(mktemp -d)
	OUTDIR=$(mktemp -d)
	GVCF_LIST=$(mktemp)
	DXGVCF_LIST=$(mktemp)
	DXGVCFIDX_LIST=$(mktemp)
	
	cd $WKDIR
	
	dx download "${vcfidx_files}" -f -o $DXGVCFIDX_LIST
	parallel -u -j $(nproc --all) --gnu parallel_download :::: $DXGVCFIDX_LIST ::: $WKDIR
	
	dx download "${vcf_files}" -f -o $DXGVCF_LIST
	
	# Now, download and index in parallel, please
	parallel -u -j $(nproc --all) --gnu dl_part_index :::: $DXGVCF_LIST ::: $WKDIR ::: $chrom ::: $OUTDIR
	
	echo "Contents of WKDIR:"
	ls -alh $WKDIR
	
	echo "Contents of OUTDIR:"
	ls -alh $OUTDIR
	
	sleep 10	
		
	# get the resources we need in /usr/share/GATK
	sudo mkdir -p /usr/share/GATK/resources
	sudo chmod -R a+rwX /usr/share/GATK
		
	dx download $(dx find data --name "GenomeAnalysisTK-3.2-2.jar" --project $DX_RESOURCES_ID --brief) -o /usr/share/GATK/GenomeAnalysisTK-3.2-2.jar
	dx download $(dx find data --name "dbsnp_137.b37.vcf.gz" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/dbsnp_137.b37.vcf.gz
	dx download $(dx find data --name "dbsnp_137.b37.vcf.gz.tbi" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/dbsnp_137.b37.vcf.gz.tbi
	dx download $(dx find data --name "human_g1k_v37_decoy.fasta" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/human_g1k_v37_decoy.fasta
	dx download $(dx find data --name "human_g1k_v37_decoy.fasta.fai" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/human_g1k_v37_decoy.fasta.fai
	dx download $(dx find data --name "human_g1k_v37_decoy.dict" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/human_g1k_v37_decoy.dict
	
    TOT_MEM=$(free -m | grep "Mem" | awk '{print $2}')
    # only ask for 90% of total system memory
    TOT_MEM=$((TOT_MEM * 9 / 10))
	VCF_TMPDIR=$(mktemp -d)
	# OK, now we can call the GATK genotypeGVCFs
	java -d64 -Xms512m -Xmx${TOT_MEM}m -jar /usr/share/GATK/GenomeAnalysisTK-3.2-2.jar \
	-T GenotypeGVCFs \
	-A QualByDepth \
	-A HaplotypeScore \
	-A MappingQualityRankSumTest \
	-A ReadPosRankSumTest \
	-A FisherStrand \
	-A GCContent \
	-A AlleleBalance \
	-A InbreedingCoeff \
	-A StrandOddsRatio \
	-A HardyWeinberg \
	-A ChromosomeCounts \
	-A VariantType \
	-A GenotypeSummaries $ADDL_CMD \
	-nt $(nproc --all) \
	-R /usr/share/GATK/resources/human_g1k_v37_decoy.fasta \
	$(ls $OUTDIR/*.vcf.gz | sed 's/^/-V /' | tr '\n' ' ') \
	--dbsnp /usr/share/GATK/resources/dbsnp_137.b37.vcf.gz \
	-o "$VCF_TMPDIR/$PREFIX.vcf.gz"
	
	
    # The following line(s) use the dx command-line tool to upload your file
    # outputs after you have created them on the local file system.  It assumes
    # that you have used the output field name for the filename for each output,
    # but you can change that behavior to suit your needs.  Run "dx upload -h"
    # to see more options to set metadata.

	vcf_fn=$(dx upload "$VCF_TMPDIR/$PREFIX.vcf.gz" --brief)
    vcf_idx_fn=$(dx upload "$VCF_TMPDIR/$PREFIX.vcf.gz.tbi" --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output vcf_out "$vcf_fn" --class=file
    dx-jobutil-add-output vcfidx_out "$vcf_idx_fn" --class=file
}

merge_vcf() {
	# set the shell to work w/ GNU parallel
	export SHELL="/bin/bash"
	
	if test -z "$PREFIX"; then
		PREFIX="combined"
	fi

	WKDIR=$(mktemp -d)
	GVCF_LIST=$(mktemp)
	DXGVCF_LIST=$(mktemp)
	DXGCVFIDX_LIST=$(mktemp)
	

	for i in "${!vcfidx_files[@]}"; do	
		echo "${vcfidx_files[$i]}" >> $DXGCVFIDX_LIST
	done
	
	parallel -u --gnu -j $(nproc --all) parallel_download :::: $DXGCVFIDX_LIST ::: $WKDIR
	
	cd $WKDIR
		
	for i in "${!vcf_files[@]}"; do
		echo "${vcf_files[$i]}" >> $DXGVCF_LIST
	done
			
	# get the resources we need in /usr/share/GATK
	sudo mkdir -p /usr/share/GATK/resources
	sudo chmod -R a+rwX /usr/share/GATK
		
	dx download $(dx find data --name "GenomeAnalysisTK-3.3-0.jar" --project $DX_RESOURCES_ID --brief) -o /usr/share/GATK/GenomeAnalysisTK-3.3-0.jar
	dx download $(dx find data --name "human_g1k_v37_decoy.fasta" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/human_g1k_v37_decoy.fasta
	dx download $(dx find data --name "human_g1k_v37_decoy.fasta.fai" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/human_g1k_v37_decoy.fasta.fai
	dx download $(dx find data --name "human_g1k_v37_decoy.dict" --project $DX_RESOURCES_ID --folder /resources --brief) -o /usr/share/GATK/resources/human_g1k_v37_decoy.dict
		
	# download the already split VCFs
	GVCF_LIST=$(mktemp)
	parallel -u -j $(nproc --all) --gnu dl_index :::: $DXGVCF_LIST ::: $WKDIR ::: $GVCF_LIST
	
	FINAL_DIR=$(mktemp -d)
	TOT_MEM=$(free -m | grep "Mem" | awk '{print $2}')
	java -d64 -Xms512m -Xmx$((TOT_MEM * 9 / 10))m -jar /usr/share/GATK/GenomeAnalysisTK-3.3-0.jar \
	-T CombineVariants -nt $(nproc --all) --assumeIdenticalSamples \
	-R /usr/share/GATK/resources/human_g1k_v37_decoy.fasta \
	$(ls -1 $WKDIR/*.vcf.gz | sed 's/^/-V /' | tr '\n' ' ') \
	-genotypeMergeOptions UNSORTED \
	-o $FINAL_DIR/$PREFIX.vcf.gz
				
	VCF_DXFN=$(dx upload ${FINAL_DIR}/$PREFIX.vcf.gz --brief)
	VCFIDX_DXFN=$(dx upload ${FINAL_DIR}/$PREFIX.vcf.gz.tbi --brief)
		
	# and upload it and we're done!
	dx-jobutil-add-output vcf_out "$VCF_DXFN" --class=file
	dx-jobutil-add-output vcfidx_out "$VCFIDX_DXFN" --class=file
}
